### ISSUE TITLE
Doesn't work with Debian 8 jessie

### ISSUE THREAD

**Issue by rhertzog** [saltstack-formulas/samba-formula#12]
With Debian 8 Jessie, the /etc/init.d/samba init script is just a wrapper around /etc/init.d/{smbd,nmbd,samba-ad-dc} and is never started at boot time and it's "masked" at the systemd level.

So you really need to enable the "smbd" service starting with Debian 8 (just like on Ubuntu). Trying to use the stock formula resulted in this for me:

```
          ID: samba
    Function: service.running
      Result: False
     Comment: Failed when setting service samba to start at boot, and the service is dead
     Changes:   
```
